// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuBkl09OlnQStII4Bxl_IYScQoRtm7oA',
    appId: '1:485728455682:android:3b91ee21641ffd03d5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    storageBucket: 'tripjoy-d309f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqYAoqX2i5xDi9cIHvZXRTveYairf0Uk',
    appId: '1:485728455682:ios:721f3228621e1333d5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    storageBucket: 'tripjoy-d309f.firebasestorage.app',
    androidClientId: '485728455682-l2k0jddb8p305pr361ll0ibhktha9k43.apps.googleusercontent.com',
    iosClientId: '485728455682-4h9sphsef1e6sk6oqep7u9bfpls624ms.apps.googleusercontent.com',
    iosBundleId: 'com.leapcompany.tripjoy',
  );
}
